### ISSUE TITLE
 Resp signal too short cannot calculate the spectral features 

### ISSUE THREAD

**Issue by maryam-EN** [Gijom/TEAP#9]
Can you help me with this problem?
![21](https://user-images.githubusercontent.com/34523762/33964737-b363a092-e06e-11e7-8410-8c7b1dc7146c.png)

**Comment by msoley** [comment]
The error message is about the mismatch between the input/output size when calculating the respiration features. The signal being too short message is just a warning that some of the features (low frequency component) might not be calculated reliably. Can you debug and ensure that the problem is from the toolbox?

**Comment by maryam-EN** [comment]
I loaded 239 trials from mahnob-hci and tried to extract their feature with "extracting_features_MAHNOB.m" . this error is what i saw. 
i don't know what to do.


    On Friday, December 15, 2017, 5:30:59 PM GMT+3:30, Mohammad Soleymani <notifications@github.com> wrote:  
 
 
The error message is about the mismatch between the input/output size when calculating the respiration features. The signal being too short message is just a warning that some of the features (low frequency component) might not be calculated reliably. Can you debug and ensure that the problem is from the toolbox?

**Comment by msoley** [comment]
Thanks for reporting this - it should work now after fixing the bug 14b214c8716922b214d582d75b501a75723a8953
